recovery_behavior_enabled: true     # default : true
controller_frequency: 2.0           # default : 10.0
controller_patience: 5.0            # default : 5.0
planner_patience: 2.0               # default : 2.0
planner_frequency: 0.05             # default : 0.15
clearing_radius: 0.6                # default : 0.6
clearing_rotation_allowed: false    # default : false
oscillation_distance: 2.0           # default : 2.0
shutdown_costmaps: false            # default : false

recovery_behaviors:
  - name: 'force_field_recovery'
    type: 'force_field_recovery/ForceFieldRecovery'
  - name: 'clear_costmap_recovery'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'simple_recovery_behavior'
    type: 'simple_recovery_behavior/SimpleRecoveryBehavior'

base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
    use_grid_path: False            # default : False
    use_dijkstra: True              # default : True
    allow_unknown: False            # default : False
    default_tolerance: 0.0          # default : 0.0
    visualize_potential: True       # default : True
    use_quadratic: True             # default : True
    use_grid_path: False            # default : False
    old_navfn_behavior: False       # default : False

#fault_detector: simple_collision_detector/SimpleCollisionDetector
fault_detector: collision_detector_diagnoser/CollisionDetectorDiagnoser

sensor_fusion:
    sensor_number: 4
    mode: 0
    filter: false

fault_recovery_behaviors:
  - name: 'simple_collision_recovery'
    type: 'simple_collision_recovery/SimpleCollisionRecovery'
  - name: 'mislocalization_collision_recovery'
    type: 'mislocalization_collision_recovery/MisLocalizationCollisionRecovery'
